
service: data
provider: aws
functions:
  graphql:
    handler: data.handler
    timeout: 5
    memory: 128
    events:
      - http:
          path: data
          method: post
          request:
            template: ${file(./request-template.json):dataQueryRequest}
      - http:
          path: schema
          method: post
          request:
            template: ${file(./request-template.json):introspectionQueryRequest}
